import MOKO as Moko
from MOSC import stars
import time

Moko.Stage(stars('*'))
Moko.Stage(stars('NEW SCRIPT'))
Moko.Stage(stars('*'))
language = Moko.Report("language", 'get', 'string', 'string', 'string')
if language == 'English(default)':
    Moko.Stage('Welcome to MOKO SE.')
    Moko.Stage('MOKO SE manages MOKO NMEA program and driver software.')
    Moko.Stage('Program control is implemented through the execution of scripts written in Python.')
    Moko.Stage('This script shows how the Stage function works.')
    Moko.Stage('Stage messages can be of a specific type. Each of the types is presented below.')
    Moko.Stage('*Info*. Outputs any information to Stage. Designated as default type', 'Info')
    Moko.Stage('*Error*. Informs about an error that occurred during script execution.', 'Error')
    Moko.Stage('*Plugin*. Displays information related to a plugin.', 'Plugin')
    Moko.Stage('*Driver*. Displays information related to the driver.', 'Driver')
    Moko.Stage('*Report*. Informs about data recording in the report.', 'Report')
    Moko.Stage('*Utility*. Reports the use of the utility.', 'Utility')
    Moko.Stage('*Messenger*. Informs about the Messenger window display.', 'Messenger')
    Moko.Stage('*Telegram*. afafafaf', 'Telegram')
    Moko.Stage('*Warning*. Informs about an warning that occurred during script execution.', 'Warning')
    time.sleep(6)
    Moko.Report("exstage", 'set', 'string', 'Absent')
    Moko.Report("exstage_1", 'set', 'string', 'The script completed successfully.')
elif language == 'Русский':
    Moko.Stage('Добро пожаловать в программу MOKO SE.')
    Moko.Stage('Программа MOKO SE осуществляет управление программой MOKO NMEA и программами-драйверами')
    Moko.Stage('Управление программой реализуется через выполнение скриптов написанных на Python.')
    Moko.Stage('Данный скрипт демонстрирует работу функции Stage.')
    Moko.Stage('Сообщения в Stage могут иметь определенный тип. Ниже представлен каждый из типов.')
    Moko.Stage('*Info*. Выводит какую-либо информацию в Stage. Обозначен как тип по умолчанию', 'Info')
    Moko.Stage('*Error*. Информирует об ошибке, произошедшей во время выполнения скрипта.', 'Error')
    Moko.Stage('*Plugin*. Выводит информацию, связанную с плагином.', 'Plugin')
    Moko.Stage('*Driver*. Выводит информацию, связанную с драйвером.', 'Driver')
    Moko.Stage('*Report*. Информирует о записи данных в отчёт.', 'Report')
    Moko.Stage('*Utility*. Сообщает об использовании утилиты.', 'Utility')
    Moko.Stage('*Messenger*. Информирует о выводе окна Messenger.', 'Messenger')
    Moko.Stage('*Telegram*. afafafaf', 'Telegram')
    Moko.Stage('*Warning*. Информирует о предупреждении, произошедшем во время выполнения скрипта.', 'Warning')
    time.sleep(6)
    Moko.Report("exstage", 'set', 'string', 'Отсутствуют')
    Moko.Report("exstage_1", 'set', 'string', 'Скрипт успешно завершён.')

Moko.Stage(stars('*'))
Moko.Stage(stars('NEXT SCRIPT'))
Moko.Stage(stars('*'))

Moko.EndScript()